# Transformacja i analiza danych kart kredytowych klientów banku /
#Credit Card Customer Data Transformation and Analysis

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sakshigoyal7/credit-card-customers")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/sakshigoyal7/credit-card-customers/1.archive...

100%|██████████| 379k/379k [00:00<00:00, 47.8MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/sakshigoyal7/credit-card-customers/versions/1

In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(os.path.join(path, "BankChurners.csv"))

In [4]:
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998

In [5]:
df.shape

(10127, 23)

In [6]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 23 columns):
 #   Column                                                                                                                              Non-Null Count  Dtype
---  ------                                                                                                                              --------------  -----
 0   CLIENTNUM                                                                                                                           10127 non-null  int64
 1   Attrition_Flag                                                                                                                      10127 non-null  object
 2   Customer_Age                                                                                                                        10127 non-null  int64
 3   Gender                                                                                                                              10127 non-null  object
 4   Dependent_count                                                                                                                     10127 non-null  int64
 5   Education_Level                                                                                                                     10127 non-null  object
 6   Marital_Status                                                                                                                      10127 non-null  object
 7   Income_Category                                                                                                                     10127 non-null  object
 8   Card_Category                                                                                                                       10127 non-null  object
 9   Months_on_book                                                                                                                      10127 non-null  int64
 10  Total_Relationship_Count                                                                                                            10127 non-null  int64
 11  Months_Inactive_12_mon                                                                                                              10127 non-null  int64
 12  Contacts_Count_12_mon                                                                                                               10127 non-null  int64
 13  Credit_Limit                                                                                                                        10127 non-null  float64
 14  Total_Revolving_Bal                                                                                                                 10127 non-null  int64
 15  Avg_Open_To_Buy                                                                                                                     10127 non-null  float64
 16  Total_Amt_Chng_Q4_Q1                                                                                                                10127 non-null  float64
 17  Total_Trans_Amt                                                                                                                     10127 non-null  int64
 18  Total_Trans_Ct                                                                                                                      10127 non-null  int64
 19  Total_Ct_Chng_Q4_Q1                                                                                                                 10127 non-null  float64
 20  Avg_Utilization_Ratio                                                                                                               10127 non-null  float64
 21  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1  10127 non-null  float64
 22  Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2  10127 non-null  float64
dtypes: float64(7), int64(10), object(6)
memory usage: 1.8+ MB

,CLIENTNUM,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
count,1.012700e+04,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000
mean,7.391776e+08,46.325960,2.346203,35.928409,3.812580,2.341167,2.455317,8631.953698,1162.814061,7469.139637,0.759941,4404.086304,64.858695,0.712222,0.274894,0.159997,0.840003
std,3.690378e+07,8.016814,1.298908,7.986416,1.554408,1.010622,1.106225,9088.776650,814.987335,9090.685324,0.219207,3397.129254,23.472570,0.238086,0.275691,0.365301,0.365301
min,7.080821e+08,26.000000,0.000000,13.000000,1.000000,0.000000,0.000000,1438.300000,0.000000,3.000000,0.000000,510.000000,10.000000,0.000000,0.000000,0.000008,0.000420
25%,7.130368e+08,41.000000,1.000000,31.000000,3.000000,2.000000,2.000000,2555.000000,359.000000,1324.500000,0.631000,2155.500000,45.000000,0.582000,0.023000,0.000099,0.999660
50%,7.179264e+08,46.000000,2.000000,36.000000,4.000000,2.000000,2.000000,4549.000000,1276.000000,3474.000000,0.736000,3899.000000,67.000000,0.702000,0.176000,0.000181,0.999820
75%,7.731435e+08,52.000000,3.000000,40.000000,5.000000,3.000000,3.000000,11067.500000,1784.000000,9859.000000,0.859000,4741.000000,81.000000,0.818000,0.503000,0.000337,0.999900
max,8.283431e+08,73.000000,5.000000,56.000000,6.000000,6.000000,6.000000,34516.000000,2517.000000,34516.000000,3.397000,18484.000000,139.000000,3.714000,0.999000,0.999580,0.999990

In [7]:
col_drop = [x for x in df.columns if x.startswith("Naive_Bayes")]
df = df.drop(columns=col_drop)

In [8]:
df.shape
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000

In [9]:
display(df.isna().sum())
print("Duplikaty: ",df.duplicated().sum())

CLIENTNUM                   0
Attrition_Flag              0
Customer_Age                0
Gender                      0
Dependent_count             0
Education_Level             0
Marital_Status              0
Income_Category             0
Card_Category               0
Months_on_book              0
Total_Relationship_Count    0
Months_Inactive_12_mon      0
Contacts_Count_12_mon       0
Credit_Limit                0
Total_Revolving_Bal         0
Avg_Open_To_Buy             0
Total_Amt_Chng_Q4_Q1        0
Total_Trans_Amt             0
Total_Trans_Ct              0
Total_Ct_Chng_Q4_Q1         0
Avg_Utilization_Ratio       0
dtype: int64

Duplikaty:  0

In [10]:
df.describe(include="object")

,Attrition_Flag,Gender,Education_Level,Marital_Status,Income_Category,Card_Category
count,10127,10127,10127,10127,10127,10127
unique,2,2,7,4,6,4
top,Existing Customer,F,Graduate,Married,Less than $40K,Blue
freq,8500,5358,3128,4687,3561,9436

In [11]:
(df == "Unknown").sum()

CLIENTNUM                      0
Attrition_Flag                 0
Customer_Age                   0
Gender                         0
Dependent_count                0
Education_Level             1519
Marital_Status               749
Income_Category             1112
Card_Category                  0
Months_on_book                 0
Total_Relationship_Count       0
Months_Inactive_12_mon         0
Contacts_Count_12_mon          0
Credit_Limit                   0
Total_Revolving_Bal            0
Avg_Open_To_Buy                0
Total_Amt_Chng_Q4_Q1           0
Total_Trans_Amt                0
Total_Trans_Ct                 0
Total_Ct_Chng_Q4_Q1            0
Avg_Utilization_Ratio          0
dtype: int64

In [12]:
df["churn"]=(df["Attrition_Flag"] == "Attrited Customer").astype(int)

In [13]:
df["churn"].mean()

np.float64(0.1606596227905599)

In [14]:
display(df["churn"].value_counts())
display(df[["Attrition_Flag", "churn"]].head(200))
display(df[["Attrition_Flag", "churn"]].head(200).sum())

churn
0    8500
1    1627
Name: count, dtype: int64

        Attrition_Flag  churn
0    Existing Customer      0
1    Existing Customer      0
2    Existing Customer      0
3    Existing Customer      0
4    Existing Customer      0
..                 ...    ...
195  Existing Customer      0
196  Existing Customer      0
197  Existing Customer      0
198  Attrited Customer      1
199  Existing Customer      0

[200 rows x 2 columns]

Attrition_Flag    Existing CustomerExisting CustomerExisting Cus...
churn                                                            14
dtype: object

In [ ]:
import os
from google.colab import drive, userdata

drive.mount("/content/drive")

NOTEBOOK = "/content/drive/MyDrive/Colab Notebooks/Python_trans.ipynb"
repo = "/content/Credit-Card-Customer-Churn-Analysis"
token = userdata.get("GITHUB_TOKEN")
url = f"https://{token}@github.com/Falisty1612/Credit-Card-Customer-Churn-Analysis.git"


if not os.path.exists(repo):
    !git clone {url} {repo} 2>&1 | sed "s/{token}/***/g"

%cd {repo}
!git config user.email ADRESEMAIL
!git config user.name "Falisty1612"
!git remote set-url origin https://github.com/Falisty1612/Credit-Card-Customer-Churn-Analysis.git


!cp "{NOTEBOOK}" .

msg = input("Test ")
!git add Python_trans.ipynb
!git commit -m "{msg}"
!git push {url} main 2>&1 | sed "s/{token}/***/g"